language: php
php:
    - 7.1

install:
    # Install Nette Code Checker
    - travis_retry composer create-project nette/code-checker temp/code-checker ^3 --no-progress
    # Install Nette Coding Standard
    - travis_retry composer create-project nette/coding-standard temp/coding-standard ^2 --no-progress

script:
    - php temp/code-checker/code-checker --strict-types
    - php temp/coding-standard/ecs check . --config temp/coding-standard/coding-standard-php71.yml

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
