language: php
php:
    - 5.6

script:
    - php code-checker/src/code-checker.php

before_script:
    - travis_retry composer create-project nette/code-checker code-checker --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
